### ISSUE TITLE
Choice of spherical projection

### ISSUE THREAD

**Issue by meder411** [ARSekkat/OmniScape#1]
Out of curiosity, what's the purpose of using an orthographic projection to distribute the dataset? You end up throwing away a lot of information in the boundaries due to the distortion and  pixel discretization. The distortion is going to exist regardless, but it seems to me that a format with expansive distortion (i.e. 1 undistorted pixel is spread into many pixels) is better than a format with contractive distortion (i.e. many undistorted pixels get condensed into a single pixel). Something like a cropped equirectangular projection (with associated metadata detailing the FOV) would serve this purpose better. It's not difficult to resample these orthographic projections to equirectangular projections, but you've already lost the data due to discretization in the original orthographic projections. Because it's all virtual data anyway, it seems there shouldn't be any limitations (other than time) to rendering the dataset to a less lossy format.

**Comment by ARSekkat** [comment]
Actually the main contribution is not the generation of 360° images. We developed a framework to generate omnidirectional images using 360° cubemap images and intrinsic parameters of a real omnidirectional camera. We used this framework and intrinsic parameters of real omnidirectional cameras to generate the dataset. It is somehow similar to record using these cameras inside the simulator. So the distortion you see in the images are exactly the same produced by the real cameras (if we do not consider the calibration error). But in addition to these images (fisheye and catadioptric) we provide 360° images used under cubemap and equirectangular projection. I just added some examples to the repository.
