### ISSUE TITLE
Does the database contain 6D pose (rotation and translation)?

### ISSUE THREAD

**Issue by NagabhushanSN95** [ARSekkat/OmniScape#3]
Hi,

Can you please clarify if your database will contain 6D pose information with both rotation and translation for every frame?
From your paper, I saw that you've orientation ground truth, which I guess will give rotation values. Will the ground truth also contain translation values?

Basically, I'm try to warp a frame to the view of next frame. For this, I'll need depth, pose of both frames and camera intrinsic matrix. Will all these data be available, at least for one of left or right camera?

**Comment by ARSekkat** [comment]
Hello @NagabhushanSN95,
The intrinsic parameters are available for all cameras and extrinsic parameters (rotation and translation) are also available for each frame.

**Comment by NagabhushanSN95** [comment]
Thank you for the reply. I had submitted the google form requesting the OmniScape dataset. But I haven't received any mail regarding that (checked spam folder too). Can you please check it once? I submitted the form again now. Thanks!
