### ISSUE TITLE
How can I simulate a fish eye camera in carla?

### ISSUE THREAD

**Issue by wongtou** [ARSekkat/OmniScape#4]
Hello, I want to know how to configure a fish eye camera in carla. 
I just found "Camera lens distortion attributes" in sensors reference of carla, but I can't get the effect I want.
![Camera lens distortion attributes](https://user-images.githubusercontent.com/24788147/190055053-c56afe87-4d2a-48ef-9d9d-4709fd342891.png)
![my fish eye camera](https://user-images.githubusercontent.com/24788147/190055613-0cbd8d79-738e-4b0d-9c47-523b2937972a.png)
![normal camera with 90fov](https://user-images.githubusercontent.com/24788147/190055698-bb86ae9b-8ea5-4cd4-9fb2-c673ee7c9e32.png)
I looking forward to your answer, thank you very much.

**Comment by ARSekkat** [comment]
Hello, we did not use the configuration of CARLA. We extracted perspective images to build a cube map 360 image and then used the framework explained in The OmniScape paper and also in the SynWoodScape paper to generate omnidirectional images.
